# Generated by Django 2.2.5 on 2020-04-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinfo',
            options={'verbose_name': '图书', 'verbose_name_plural': '图书'},
        ),
        migrations.AlterModelOptions(
            name='heroinfo',
            options={'verbose_name': '英雄', 'verbose_name_plural': '英雄'},
        ),
        migrations.AlterModelTable(
            name='bookinfo',
            table='tb_books',
        ),
        migrations.AlterModelTable(
            name='heroinfo',
            table='tb_heros',
        ),
    ]
